# Generated by Django 2.2.5 on 2019-09-29 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default='none@none.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timetable',
            name='location',
            field=models.CharField(default='deafult location', max_length=50),
            preserve_default=False,
        ),
    ]
