# Generated by Django 2.2.5 on 2019-09-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190929_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='email',
            field=models.EmailField(default='none@none.com', max_length=254),
            preserve_default=False,
        ),
    ]
